environment:
  PROJECT_NAME: duplicate_finder_python
  MAJOR: 0
  MINOR: 0
  matrix:
    - job_name: MS build
      appveyor_build_worker_image: Visual Studio 2019
    - job_name: Linux build
      appveyor_build_worker_image: Ubuntu2004

version: ${MAJOR}.${MINOR}.{build}

matrix:
  fast_finish: true

skip_tags: true

for:
  - matrix:
      only:
        - job_name: MS build

    before_build:
      - python -m pip install --upgrade pip
      - python -m pip install wheel
      - ps: Invoke-WebRequest -Uri "https://files.pythonhosted.org/packages/18/11/241dce340c7bbda01352cf23c00b9d07f6e6395208b0d2011a4ac9d2e1d0/PySide6-6.5.1-cp37-abi3-win_amd64.whl" -OutFile "PySide6-6.5.1-cp37-abi3-win_amd64.whl"
      - python -m pip install PySide6-6.5.1-cp37-abi3-win_amd64.whl
      - python -m pip install -r requirements.txt

    build_script:
      - python -m pip install pyinstaller
      - $HOME/.local/bin/pyinstaller duplicate_finder.spec

    artifacts:
      - path: dist/duplicate_finder.exe
        name: $PROJECT_NAME-$APPVEYOR_BUILD_VERSION-Windows

    deploy:
      - provider: GitHub
        skip_cleanup: true
        release: $APPVEYOR_BUILD_VERSION
        auth_token: $GITHUB_TOKEN
        artifact: $PROJECT_NAME-$APPVEYOR_BUILD_VERSION-Windows
        draft: false
        prerelease: false


  - matrix:
      only:
        - job_name: Linux build

    before_build:
      - sudo apt-get update -qq
      - sudo apt-get install -y python3 python3-pip
      - python3 -m pip install --upgrade pip
      - python3 -m pip install -r requirements.txt

    build_script:
      - python3 -m pip install pyinstaller
      - $HOME/.local/bin/pyinstaller duplicate_finder.spec

    artifacts:
      - path: dist/duplicate_finder
        name: $PROJECT_NAME-$APPVEYOR_BUILD_VERSION-Linux

    deploy:
      - provider: GitHub
        skip_cleanup: true
        release: $APPVEYOR_BUILD_VERSION
        auth_token: $GITHUB_TOKEN
        artifact: $PROJECT_NAME-$APPVEYOR_BUILD_VERSION-Linux
        draft: false
        prerelease: false


