name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+_release'

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            artifact: "duplicate_finder"
          - os: windows-latest
            artifact: "duplicate_finder.exe"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Update version
        id: update_version
        run: |
          python3 - <<EOF
          import os
          import re

          version = '${{ github.ref }}'
          version = version.replace('refs/tags/', '')
          version_parts = re.findall(r'\d+', version)
          major = version_parts[0]
          minor = version_parts[1]
          patch_with_suffix = version_parts[2]
          patch = patch_with_suffix.split('_')[0]
          build_number = os.getenv('BUILD_NUMBER')

          with open('version.py', 'w') as f:
              f.write(f'APP_VERSION = "{major}.{minor}.{patch}"\n')
              f.write(f'BUILD_NUMBER = "{build_number}"\n')

          with open('version.py', 'r') as f:
              print(f.read())
          EOF


      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libegl1 libegl1-mesa python2-dev python3-dev gcc -y
          fi
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          cat version.py
          python -m pip install pyinstaller
        shell: bash

      - name: Build
        run: |
          pyinstaller duplicate_finder.spec

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/duplicate_finder,dist/duplicate_finder.exe"
