name: Tests

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            sudo apt update
            sudo apt install libegl1 libegl1-mesa python2-dev python3-dev gcc -y
          fi
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        shell: bash
      - name: Test
        run: |
          python -m pytest ./tests
